
import React, { useState } from 'react';
import { useStore } from '../context/StoreContext';
import { Account, AccountType, AccountTransactionType } from '../types';
import { Wallet, TrendingUp, TrendingDown, Plus, ArrowRightLeft, DollarSign, Landmark, ChevronRight } from 'lucide-react';

const AccountsPage: React.FC = () => {
  const { accounts, accountTransactions, addAccount, registerAccountTransaction, transferFunds, formatCurrency } = useStore();
  const [view, setView] = useState<'DASHBOARD' | 'LEDGER'>('DASHBOARD');
  const [selectedAccountId, setSelectedAccountId] = useState<string | null>(null);
  const [isAddAccountOpen, setIsAddAccountOpen] = useState(false);
  const [isCashInOpen, setIsCashInOpen] = useState(false);
  const [isCashOutOpen, setIsCashOutOpen] = useState(false);
  const [isTransferOpen, setIsTransferOpen] = useState(false);
  const [newAccount, setNewAccount] = useState<Partial<Account>>({ name: '', type: AccountType.CASH, openingBalance: 0, status: 'Active', description: '' });
  const [transactionForm, setTransactionForm] = useState({ accountId: '', toAccountId: '', amount: '', description: '', date: new Date().toISOString().split('T')[0] });

  const totalCash = accounts.filter(a => a.type === AccountType.CASH).reduce((acc, curr) => acc + curr.currentBalance, 0);
  const totalBank = accounts.filter(a => a.type === AccountType.BANK).reduce((acc, curr) => acc + curr.currentBalance, 0);
  const today = new Date().toISOString().split('T')[0];
  const todayIn = accountTransactions.filter(t => t.date.startsWith(today) && (t.type === 'CASH_IN' || t.type === 'TRANSFER_IN')).reduce((acc, t) => acc + t.amount, 0);
  const todayOut = accountTransactions.filter(t => t.date.startsWith(today) && (t.type === 'CASH_OUT' || t.type === 'TRANSFER_OUT')).reduce((acc, t) => acc + t.amount, 0);

  const handleAddAccount = (e: React.FormEvent) => { e.preventDefault(); if (newAccount.name) { addAccount({ id: `acc_${Date.now()}`, name: newAccount.name, type: newAccount.type as AccountType, openingBalance: Number(newAccount.openingBalance), currentBalance: Number(newAccount.openingBalance), status: 'Active', description: newAccount.description, bankName: newAccount.bankName }); setIsAddAccountOpen(false); setNewAccount({ name: '', type: AccountType.CASH, openingBalance: 0, status: 'Active' }); } };
  const handleCashIn = (e: React.FormEvent) => { e.preventDefault(); registerAccountTransaction(transactionForm.accountId, AccountTransactionType.CASH_IN, Number(transactionForm.amount), transactionForm.description, new Date(transactionForm.date).toISOString(), 'ADJUSTMENT'); setIsCashInOpen(false); resetForm(); };
  const handleCashOut = (e: React.FormEvent) => { e.preventDefault(); const acc = accounts.find(a => a.id === transactionForm.accountId); if(acc && acc.currentBalance < Number(transactionForm.amount)) { alert("Insufficient Funds!"); return; } registerAccountTransaction(transactionForm.accountId, AccountTransactionType.CASH_OUT, Number(transactionForm.amount), transactionForm.description, new Date(transactionForm.date).toISOString(), 'EXPENSE'); setIsCashOutOpen(false); resetForm(); };
  const handleTransfer = (e: React.FormEvent) => { e.preventDefault(); if(transactionForm.accountId === transactionForm.toAccountId) { alert("Cannot transfer to same account"); return; } const acc = accounts.find(a => a.id === transactionForm.accountId); if(acc && acc.currentBalance < Number(transactionForm.amount)) { alert("Insufficient Funds in Source Account!"); return; } transferFunds(transactionForm.accountId, transactionForm.toAccountId, Number(transactionForm.amount), new Date(transactionForm.date).toISOString(), transactionForm.description); setIsTransferOpen(false); resetForm(); };
  const resetForm = () => setTransactionForm({ accountId: '', toAccountId: '', amount: '', description: '', date: new Date().toISOString().split('T')[0] });

  const selectedAccount = accounts.find(a => a.id === selectedAccountId);
  const selectedTransactions = accountTransactions.filter(t => t.accountId === selectedAccountId).sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

  if (view === 'LEDGER' && selectedAccount) {
    return (
      <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
        <div className="flex items-center justify-between"><button onClick={() => setView('DASHBOARD')} className="text-slate-500 hover:text-slate-700 flex items-center gap-2"><ChevronRight className="rotate-180" size={20} /> Back to Dashboard</button><h1 className="text-2xl font-bold dark:text-white">{selectedAccount.name} Ledger</h1></div>
        <div className="bg-white dark:bg-slate-800 p-6 rounded-xl shadow-sm border border-slate-100 dark:border-slate-700 grid grid-cols-1 md:grid-cols-3 gap-6"><div className="p-4 bg-brand-50 dark:bg-brand-900/20 rounded-lg"><span className="text-sm text-brand-600 dark:text-brand-300 font-medium">Current Balance</span><div className="text-2xl font-bold text-brand-700 dark:text-brand-400 mt-1">{formatCurrency(selectedAccount.currentBalance)}</div></div><div className="p-4 bg-emerald-50 dark:bg-emerald-900/20 rounded-lg"><span className="text-sm text-emerald-600 dark:text-emerald-300 font-medium">Total In</span><div className="text-2xl font-bold text-emerald-700 dark:text-emerald-400 mt-1">{formatCurrency(selectedTransactions.filter(t => t.type.includes('IN')).reduce((a,c) => a + c.amount, 0))}</div></div><div className="p-4 bg-red-50 dark:bg-red-900/20 rounded-lg"><span className="text-sm text-red-600 dark:text-red-300 font-medium">Total Out</span><div className="text-2xl font-bold text-red-700 dark:text-red-400 mt-1">{formatCurrency(selectedTransactions.filter(t => t.type.includes('OUT')).reduce((a,c) => a + c.amount, 0))}</div></div></div>
        <div className="bg-white dark:bg-slate-800 rounded-xl shadow-sm border border-slate-100 dark:border-slate-700 overflow-hidden"><table className="w-full text-left border-collapse text-sm"><thead className="bg-slate-50 dark:bg-slate-700"><tr><th className="p-4 font-semibold text-slate-600 dark:text-slate-300">Date</th><th className="p-4 font-semibold text-slate-600 dark:text-slate-300">Description</th><th className="p-4 font-semibold text-slate-600 dark:text-slate-300">Type</th><th className="p-4 font-semibold text-slate-600 dark:text-slate-300 text-right">Debit</th><th className="p-4 font-semibold text-slate-600 dark:text-slate-300 text-right">Credit</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-700">{selectedTransactions.map(t => { const isCredit = t.type.includes('IN'); return (<tr key={t.id} className="hover:bg-slate-50 dark:hover:bg-slate-700/50"><td className="p-4 dark:text-slate-300">{new Date(t.date).toLocaleDateString()}</td><td className="p-4"><div className="font-medium dark:text-slate-200">{t.description}</div>{t.referenceModule && <div className="text-xs text-slate-500 rounded bg-slate-100 dark:bg-slate-700 w-fit px-1">{t.referenceModule} #{t.referenceId}</div>}</td><td className="p-4 text-xs font-medium dark:text-slate-400">{t.type}</td><td className="p-4 text-right text-red-600">{!isCredit ? formatCurrency(t.amount) : '-'}</td><td className="p-4 text-right text-emerald-600">{isCredit ? formatCurrency(t.amount) : '-'}</td></tr>) })}</tbody></table></div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h1 className="text-2xl font-bold text-slate-800 dark:text-slate-100">Accounts & Cash</h1><p className="text-slate-500 dark:text-slate-400">Manage cash drawers, bank accounts, and transfers.</p></div><div className="flex gap-2"><button onClick={() => setIsCashInOpen(true)} className="bg-emerald-600 hover:bg-emerald-700 text-white px-3 py-2 rounded-lg flex items-center gap-2 text-sm shadow-sm transition-all"><TrendingUp size={16} /> Cash In</button><button onClick={() => setIsCashOutOpen(true)} className="bg-red-600 hover:bg-red-700 text-white px-3 py-2 rounded-lg flex items-center gap-2 text-sm shadow-sm transition-all"><TrendingDown size={16} /> Cash Out</button><button onClick={() => setIsTransferOpen(true)} className="bg-blue-600 hover:bg-blue-700 text-white px-3 py-2 rounded-lg flex items-center gap-2 text-sm shadow-sm transition-all"><ArrowRightLeft size={16} /> Transfer</button><button onClick={() => setIsAddAccountOpen(true)} className="bg-slate-800 dark:bg-slate-700 hover:bg-slate-900 text-white px-3 py-2 rounded-lg flex items-center gap-2 text-sm shadow-sm transition-all"><Plus size={16} /> New Account</button></div></div>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6"><div className="bg-white dark:bg-slate-800 p-6 rounded-xl shadow-sm border border-slate-100 dark:border-slate-700 flex items-center justify-between"><div><p className="text-sm font-medium text-slate-500 dark:text-slate-400">Total Cash</p><h3 className="text-2xl font-bold text-slate-800 dark:text-slate-100 mt-1">{formatCurrency(totalCash)}</h3></div><div className="p-3 bg-emerald-100 text-emerald-600 rounded-lg"><DollarSign size={24} /></div></div><div className="bg-white dark:bg-slate-800 p-6 rounded-xl shadow-sm border border-slate-100 dark:border-slate-700 flex items-center justify-between"><div><p className="text-sm font-medium text-slate-500 dark:text-slate-400">Bank Balance</p><h3 className="text-2xl font-bold text-slate-800 dark:text-slate-100 mt-1">{formatCurrency(totalBank)}</h3></div><div className="p-3 bg-blue-100 text-blue-600 rounded-lg"><Landmark size={24} /></div></div><div className="bg-white dark:bg-slate-800 p-6 rounded-xl shadow-sm border border-slate-100 dark:border-slate-700 flex items-center justify-between"><div><p className="text-sm font-medium text-slate-500 dark:text-slate-400">Today In</p><h3 className="text-2xl font-bold text-emerald-600 mt-1">+{formatCurrency(todayIn)}</h3></div><div className="p-3 bg-emerald-50 text-emerald-500 rounded-lg"><TrendingUp size={24} /></div></div><div className="bg-white dark:bg-slate-800 p-6 rounded-xl shadow-sm border border-slate-100 dark:border-slate-700 flex items-center justify-between"><div><p className="text-sm font-medium text-slate-500 dark:text-slate-400">Today Out</p><h3 className="text-2xl font-bold text-red-600 mt-1">-{formatCurrency(todayOut)}</h3></div><div className="p-3 bg-red-50 text-red-500 rounded-lg"><TrendingDown size={24} /></div></div></div>
      <div className="bg-white dark:bg-slate-800 rounded-xl shadow-sm border border-slate-100 dark:border-slate-700 overflow-hidden"><div className="p-6 border-b border-slate-100 dark:border-slate-700"><h3 className="font-bold text-lg dark:text-white">Active Accounts</h3></div><table className="w-full text-left border-collapse"><thead className="bg-slate-50 dark:bg-slate-700/50 text-slate-500 dark:text-slate-400 text-sm"><tr><th className="p-4 font-semibold">Account Name</th><th className="p-4 font-semibold">Type</th><th className="p-4 font-semibold">Bank Name</th><th className="p-4 font-semibold text-right">Balance</th><th className="p-4 font-semibold text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-700">{accounts.map(acc => (<tr key={acc.id} className="hover:bg-slate-50 dark:hover:bg-slate-700/50 transition-colors"><td className="p-4"><div className="font-medium text-slate-800 dark:text-slate-200">{acc.name}</div><div className="text-xs text-slate-500">{acc.description}</div></td><td className="p-4"><span className={`px-2 py-1 rounded text-xs font-medium ${acc.type === AccountType.CASH ? 'bg-emerald-100 text-emerald-700' : 'bg-blue-100 text-blue-700'}`}>{acc.type}</span></td><td className="p-4 text-slate-600 dark:text-slate-400 text-sm">{acc.bankName || '-'}</td><td className="p-4 text-right font-bold text-slate-700 dark:text-slate-200">{formatCurrency(acc.currentBalance)}</td><td className="p-4 text-right"><button onClick={() => { setSelectedAccountId(acc.id); setView('LEDGER'); }} className="text-brand-600 hover:text-brand-700 text-sm font-medium flex items-center gap-1 justify-end">View Ledger <ChevronRight size={16} /></button></td></tr>))}</tbody></table></div>
      {isAddAccountOpen && (<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="bg-white dark:bg-slate-800 rounded-xl w-full max-w-md p-6 shadow-2xl"><h2 className="text-xl font-bold mb-4 dark:text-white">Add New Account</h2><form onSubmit={handleAddAccount} className="space-y-4"><div><label className="text-sm dark:text-slate-300">Account Name</label><input required className="w-full p-2 border rounded dark:bg-slate-700 dark:border-slate-600 dark:text-white" value={newAccount.name} onChange={e => setNewAccount({...newAccount, name: e.target.value})} /></div><div><label className="text-sm dark:text-slate-300">Type</label><select className="w-full p-2 border rounded dark:bg-slate-700 dark:border-slate-600 dark:text-white" value={newAccount.type} onChange={e => setNewAccount({...newAccount, type: e.target.value as AccountType})}><option value={AccountType.CASH}>Cash</option><option value={AccountType.BANK}>Bank</option><option value={AccountType.WALLET}>Wallet</option></select></div>{newAccount.type === AccountType.BANK && (<div><label className="text-sm dark:text-slate-300">Bank Name</label><input className="w-full p-2 border rounded dark:bg-slate-700 dark:border-slate-600 dark:text-white" value={newAccount.bankName} onChange={e => setNewAccount({...newAccount, bankName: e.target.value})} /></div>)}<div><label className="text-sm dark:text-slate-300">Opening Balance</label><input type="number" className="w-full p-2 border rounded dark:bg-slate-700 dark:border-slate-600 dark:text-white" value={newAccount.openingBalance} onChange={e => setNewAccount({...newAccount, openingBalance: Number(e.target.value)})} /></div><div><label className="text-sm dark:text-slate-300">Description</label><textarea className="w-full p-2 border rounded dark:bg-slate-700 dark:border-slate-600 dark:text-white" value={newAccount.description} onChange={e => setNewAccount({...newAccount, description: e.target.value})} /></div><div className="flex justify-end gap-3 pt-2"><button type="button" onClick={() => setIsAddAccountOpen(false)} className="text-slate-500">Cancel</button><button type="submit" className="bg-brand-600 text-white px-4 py-2 rounded">Create Account</button></div></form></div></div>)}
      {isCashInOpen && (<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="bg-white dark:bg-slate-800 rounded-xl w-full max-w-md p-6 shadow-2xl"><h2 className="text-xl font-bold mb-4 text-emerald-600 flex items-center gap-2"><TrendingUp /> Cash In / Receive</h2><form onSubmit={handleCashIn} className="space-y-4"><div><label className="text-sm dark:text-slate-300">Deposit To Account</label><select required className="w-full p-2 border rounded dark:bg-slate-700 dark:border-slate-600 dark:text-white" value={transactionForm.accountId} onChange={e => setTransactionForm({...transactionForm, accountId: e.target.value})}><option value="">Select Account</option>{accounts.map(a => <option key={a.id} value={a.id}>{a.name} ({formatCurrency(a.currentBalance)})</option>)}</select></div><div><label className="text-sm dark:text-slate-300">Amount</label><input required type="number" className="w-full p-2 border rounded dark:bg-slate-700 dark:border-slate-600 dark:text-white" value={transactionForm.amount} onChange={e => setTransactionForm({...transactionForm, amount: e.target.value})} /></div><div><label className="text-sm dark:text-slate-300">Description / Reason</label><input required className="w-full p-2 border rounded dark:bg-slate-700 dark:border-slate-600 dark:text-white" value={transactionForm.description} onChange={e => setTransactionForm({...transactionForm, description: e.target.value})} /></div><div><label className="text-sm dark:text-slate-300">Date</label><input type="date" className="w-full p-2 border rounded dark:bg-slate-700 dark:border-slate-600 dark:text-white" value={transactionForm.date} onChange={e => setTransactionForm({...transactionForm, date: e.target.value})} /></div><div className="flex justify-end gap-3 pt-2"><button type="button" onClick={() => setIsCashInOpen(false)} className="text-slate-500">Cancel</button><button type="submit" className="bg-emerald-600 text-white px-4 py-2 rounded">Confirm Deposit</button></div></form></div></div>)}
      {isCashOutOpen && (<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="bg-white dark:bg-slate-800 rounded-xl w-full max-w-md p-6 shadow-2xl"><h2 className="text-xl font-bold mb-4 text-red-600 flex items-center gap-2"><TrendingDown /> Cash Out / Expense</h2><form onSubmit={handleCashOut} className="space-y-4"><div><label className="text-sm dark:text-slate-300">Withdraw From Account</label><select required className="w-full p-2 border rounded dark:bg-slate-700 dark:border-slate-600 dark:text-white" value={transactionForm.accountId} onChange={e => setTransactionForm({...transactionForm, accountId: e.target.value})}><option value="">Select Account</option>{accounts.map(a => <option key={a.id} value={a.id}>{a.name} ({formatCurrency(a.currentBalance)})</option>)}</select></div><div><label className="text-sm dark:text-slate-300">Amount</label><input required type="number" className="w-full p-2 border rounded dark:bg-slate-700 dark:border-slate-600 dark:text-white" value={transactionForm.amount} onChange={e => setTransactionForm({...transactionForm, amount: e.target.value})} /></div><div><label className="text-sm dark:text-slate-300">Description / Reason</label><input required className="w-full p-2 border rounded dark:bg-slate-700 dark:border-slate-600 dark:text-white" value={transactionForm.description} onChange={e => setTransactionForm({...transactionForm, description: e.target.value})} /></div><div><label className="text-sm dark:text-slate-300">Date</label><input type="date" className="w-full p-2 border rounded dark:bg-slate-700 dark:border-slate-600 dark:text-white" value={transactionForm.date} onChange={e => setTransactionForm({...transactionForm, date: e.target.value})} /></div><div className="flex justify-end gap-3 pt-2"><button type="button" onClick={() => setIsCashOutOpen(false)} className="text-slate-500">Cancel</button><button type="submit" className="bg-red-600 text-white px-4 py-2 rounded">Confirm Withdraw</button></div></form></div></div>)}
      {isTransferOpen && (<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="bg-white dark:bg-slate-800 rounded-xl w-full max-w-md p-6 shadow-2xl"><h2 className="text-xl font-bold mb-4 text-blue-600 flex items-center gap-2"><ArrowRightLeft /> Transfer Funds</h2><form onSubmit={handleTransfer} className="space-y-4"><div className="grid grid-cols-2 gap-4"><div><label className="text-sm dark:text-slate-300">From</label><select required className="w-full p-2 border rounded dark:bg-slate-700 dark:border-slate-600 dark:text-white" value={transactionForm.accountId} onChange={e => setTransactionForm({...transactionForm, accountId: e.target.value})}><option value="">Source</option>{accounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></div><div><label className="text-sm dark:text-slate-300">To</label><select required className="w-full p-2 border rounded dark:bg-slate-700 dark:border-slate-600 dark:text-white" value={transactionForm.toAccountId} onChange={e => setTransactionForm({...transactionForm, toAccountId: e.target.value})}><option value="">Destination</option>{accounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></div></div><div><label className="text-sm dark:text-slate-300">Amount</label><input required type="number" className="w-full p-2 border rounded dark:bg-slate-700 dark:border-slate-600 dark:text-white" value={transactionForm.amount} onChange={e => setTransactionForm({...transactionForm, amount: e.target.value})} /></div><div><label className="text-sm dark:text-slate-300">Note</label><input required className="w-full p-2 border rounded dark:bg-slate-700 dark:border-slate-600 dark:text-white" value={transactionForm.description} onChange={e => setTransactionForm({...transactionForm, description: e.target.value})} /></div><div><label className="text-sm dark:text-slate-300">Date</label><input type="date" className="w-full p-2 border rounded dark:bg-slate-700 dark:border-slate-600 dark:text-white" value={transactionForm.date} onChange={e => setTransactionForm({...transactionForm, date: e.target.value})} /></div><div className="flex justify-end gap-3 pt-2"><button type="button" onClick={() => setIsTransferOpen(false)} className="text-slate-500">Cancel</button><button type="submit" className="bg-blue-600 text-white px-4 py-2 rounded">Transfer Now</button></div></form></div></div>)}
    </div>
  );
};

export default AccountsPage;
